force-app/main/default/objects/ErrorHandlerSettings__c/ErrorHandlerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ErrorHandlerSettings</label>
</CustomObject>

force-app/main/default/objects/ErrorHandlerSettings__c/fields/Attempts__c.field-meta.xml
<CustomField>
    <fullName>Attempts__c</fullName>
    <label>Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GenericErrorHandlerExecutor.cls
/**
 * Created by Sergey Krivorotov.
 */

public with sharing class GenericErrorHandlerExecutor {

    public static void execute(GenericErrorHandler errorHandler) {
        ErrorHandlerSettings__c settings = ErrorHandlerSettings__c.getValues(errorHandler.getType().getName());
        errorHandler.setInterval(settings.Interval__c.intValue());
        if (errorHandler.getStatus() != 'Success' && errorHandler.attempts < settings.Attempts__c.intValue()) {
            System.debug('Status: ' + errorHandler.getStatus());
            System.debug('Attempts: ' + errorHandler.attempts);
            errorHandler.attempts++;
//            errorHandler.execute();
            errorHandler.schedule();
        }
    }
}